highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
permalink: posts/:title
gems: [jekyll-paginate]
paginate: 6
paginate_path: "posts/page:num"
navigation:
    - text: photo essays
      identity: photo_essays
      url: /
    - text: posts
      url: /posts/
    - text: about
      url: /about/
name: rpk.io
email: kostis.rpk@gmail
url: https://rpk.io
description: "Contemporary urban and sub-urban landscapes which emit the feeling of loneliness, abandonment and curiosity. Film photography - Software development - Ruby - Ruby on Rails"
google_plus: https://plus.google.com/106674914836183072429
twitter: rpk0_
github: rpk0
flickr: rp0
instagram: rpk0_
facebook_page: https://www.facebook.com/pages/rpkio/325550960986028
gravatar_url: https://s.gravatar.com/avatar/8bc43bee9040db6434f0842501858358?s=80
